version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: >
      sh -c "cd /root/my_app/apps && 
                python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: db